### PR TITLE
add ability to run LCM on CPU

### PR DESCRIPTION
**Pull request by by321**

### CODE REVIEW

**Comment by ljleb** [comment]
I mentioned this in #22, IMO we should consider using the properties exposed by the webui in `modules.devices` instead of adding a new checkbox.

**Comment by 0xbitches** [comment]
I think people who wants to run on CPUs are not necessarily running A1111 itself on CPU. 
In my opinion, having a checkbox for the user to choose is still the better approach.

**Comment by 0xbitches** [comment]
@by321 @ljleb Thanks for the contribution. I have decided to use `modules.devices` by default, then override it with cpu should the user choose to.

**Comment by by321** [comment]
Just a note: I just found out modern CPUs have support FP16 (although I couldn't get it work on my machine), so maybe automatically override FP16 with FP32 in CPU mode isn't a good idea.

**Pull request closed without merging**
